-- 코드를 입력하세요
WITH table1 as(
SELECT *, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS D FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
    )
SELECT CAR_ID, D AS AVERAGE_DURATION FROM table1 a
WHERE D >= 7
ORDER BY D DESC, CAR_ID DESC