-- 코드를 입력하세요
WITH table1 as(
SELECT MEMBER_ID,
       DATE_FORMAT(DATE_OF_BIRTH,'%m') AS DATE_OF_BIRTH 
       from MEMBER_PROFILE 
               )
SELECT m.MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(m.DATE_OF_BIRTH,'%Y-%m-%d')as DATE_OF_BIRTH from table1 a
INNER JOIN MEMBER_PROFILE m ON a.MEMBER_ID = m.MEMBER_ID
WHERE a.DATE_OF_BIRTH = 03 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY m.MEMBER_ID